#!/usr/bin/env php
<?php

// Arguments
if (empty($argv[1])) die("Inform the ID of your Amazon Whishlist.\n");
if (empty($argv[2])) $argv[2] = 'US';
if (empty($argv[3])) $argv[3] = 'amazon_whishlist_' . date('Ymd_His') . '.csv';

// Requiring composer autoloader (local or global)
foreach ([__DIR__ . '/../../autoload.php', __DIR__ . '/vendor/autoload.php'] as $file) {
    if (file_exists($file)) {
        define('COMPOSER_AUTOLOADER', $file);
        break;
    }
}

if (!defined('COMPOSER_AUTOLOADER')) {
    die(
        'You need to set up the project dependencies using the following commands:' . PHP_EOL .
        'php -r "readfile(\'https://getcomposer.org/installer\');" | php' . PHP_EOL .
        'php composer.phar install' . PHP_EOL
    );
}

require COMPOSER_AUTOLOADER;

$logger = new \AmazonWishlistExporter\Logger\StandardOutputLogger();
$client = new \GuzzleHttp\Client();
$wishlistId = $argv[1];
$countryCode = $argv[2];
$pathToSave = $argv[3];

$command = new \AmazonWishlistExporter\Command\ExportCommand($countryCode, $wishlistId, $client, $logger, $pathToSave);
$items = $command->execute();
